version: '2.1'
services:
  rsyslog:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_ENV: 1
    network_mode: host
    volumes:
      - ./work:/work
      - ./config:/config

